sudo: false

language: node_js
node_js:
  - stable

addons:
  chrome: stable

install:
  - yarn install --no-lockfile --non-interactive

jobs:
  fail_fast: true

  include:
    - stage: tests
      name: "Linting"
      script: yarn lint
    - name: "Tests"
      script: yarn test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/53eb4761db0a361a94a1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
