sudo: required
dist: trusty
language: node_js

node_js:
  - "6"

before_install:
  - "npm install phantomjs-prebuilt"
  - "phantomjs --version"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - npm install

script:
  - npm test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/53eb4761db0a361a94a1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
