name: CI

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 10.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint:ts

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 10.x
      - run: yarn install --frozen-lockfile
      - run: yarn test